### ISSUE TITLE
[Env: cli] Environment support for `apps ls`

### ISSUE THREAD

**Issue by dianadoherty** [meroxa/cli#594]
## Metadata 

- [Implementation plan](https://www.notion.so/meroxa/Environments-Turbine-Support-Implementation-Plan-8aa02e78eaec453ab6b47ff9d5c2a9ed)

**Depends on**

- [x] https://github.com/meroxa/meroxa-go/issues/153

## Context 

Ensure that `meroxa apps ls` reports an App's Environment information

## Acceptance 

- [x]  Add an Environment name column when listing Environments with: `meroxa apps ls` 
    - Note: a column doesn't need to be reported if customer's don't have the Environments feature enabled

**Comment by raulb** [comment]
@dianadoherty rather than relying on feature flag, I'm going to rely on the information that's stored. i.e.: if a user doesn't have the environments feature flag enabled, applications shouldn't have the environment associated. If it does (and different than common), I think it's worth showing the information. Let me know if that works for you.
